[features]
seeds = false
skip-lint = false
[programs.localnet]
zero_copy = "DsqmUY3txpP3RNLxjHUWEepFTHiZBK6BMqaucqJD1Jzh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/jonasmac2/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
